# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-13 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('AccountID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=11, unique=True)),
                ('username', models.CharField(max_length=10, null=True)),
                ('channel', models.IntegerField(null=True)),
                ('from_id', models.CharField(max_length=11, null=True)),
                ('token', models.CharField(max_length=20, null=True)),
                ('time', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('access_token', models.CharField(blank=True, max_length=100)),
                ('refresh_token', models.CharField(blank=True, max_length=100)),
                ('expires_in', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ('AccountID',),
            },
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileImgURL', models.URLField()),
                ('NickName', models.CharField(max_length=5)),
                ('PhoneNumber', models.IntegerField()),
                ('CarrierCode', models.IntegerField(default=0)),
                ('InviterID', models.IntegerField()),
                ('Address', models.CharField(max_length=30)),
                ('Mail', models.EmailField(max_length=254)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AccountInfo',
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountName', models.CharField(max_length=10)),
                ('AccountLevelCode', models.IntegerField(default=0)),
                ('UserID', models.IntegerField()),
                ('UserName', models.CharField(max_length=10)),
                ('GenderCode', models.IntegerField(default=0)),
                ('UserImgURL', models.URLField()),
                ('RegisterDate', models.DateTimeField()),
                ('JoinIP', models.CharField(max_length=39)),
                ('ChannelCode', models.IntegerField()),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountStatus', models.IntegerField(default=0)),
                ('NameAuthStatus', models.IntegerField(default=0)),
                ('ContactStatus', models.IntegerField(default=0)),
                ('CarrierAuthStatus', models.IntegerField(default=0)),
                ('DeviceAuthStatus', models.IntegerField(default=0)),
                ('BankCardAuthStatus', models.IntegerField(default=0)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountStatus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AccountStatus',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('udid', models.IntegerField()),
                ('device_name', models.CharField(max_length=30)),
                ('device_mode', models.CharField(max_length=30)),
                ('system_version', models.CharField(max_length=10)),
                ('app_version', models.CharField(max_length=10)),
                ('jail_broken', models.IntegerField(default=0)),
                ('access_gps', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('time', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Idc_Host',
            fields=[
                ('idc_name', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('lan_ip', models.CharField(max_length=16, null=True)),
                ('wan_ip', models.CharField(max_length=16, null=True)),
                ('hid', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=16, null=True)),
                ('cpu_type', models.CharField(max_length=30, null=True)),
                ('cpu_number', models.IntegerField(null=True)),
                ('memory_size', models.CharField(max_length=20, null=True)),
                ('disk_size', models.CharField(max_length=20, null=True)),
                ('disk_type', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateField()),
            ],
            options={
                'db_table': 'Idc_Host',
            },
        ),
        migrations.CreateModel(
            name='Native_Host',
            fields=[
                ('idc_name', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('lan_ip', models.CharField(max_length=16, null=True)),
                ('wan_ip', models.CharField(max_length=16, null=True)),
                ('hid', models.CharField(max_length=30, null=True)),
                ('Cabinet', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=16, null=True)),
                ('cpu_type', models.CharField(max_length=30, null=True)),
                ('cpu_number', models.IntegerField(null=True)),
                ('memory_size', models.CharField(max_length=20, null=True)),
                ('disk_size', models.CharField(max_length=20, null=True)),
                ('disk_type', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateField()),
            ],
            options={
                'db_table': 'Native_Host',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=30)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Product_cmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=16, null=True)),
                ('cmd_name', models.CharField(max_length=16, null=True)),
                ('cmd_type', models.CharField(max_length=16, null=True)),
                ('owner', models.CharField(max_length=16, null=True)),
                ('last_time', models.DateField()),
            ],
            options={
                'db_table': 'Product_cmd',
            },
        ),
        migrations.CreateModel(
            name='Product_Host',
            fields=[
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=16, null=True)),
                ('lan_ip', models.CharField(max_length=16, null=True)),
                ('wan_ip', models.CharField(max_length=16, null=True)),
                ('hid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=16, null=True)),
                ('cpu_type', models.CharField(max_length=30, null=True)),
                ('cpu_number', models.IntegerField(null=True)),
                ('memory_size', models.CharField(max_length=20, null=True)),
                ('disk_size', models.CharField(max_length=20, null=True)),
                ('disk_type', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateField()),
                ('native_host', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'Product_Host',
            },
        ),
        migrations.CreateModel(
            name='Product_Server',
            fields=[
                ('server_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=16, null=True)),
                ('server_type', models.CharField(max_length=16, null=True)),
                ('server_ip', models.CharField(max_length=30, null=True)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=16, null=True)),
                ('hid', models.CharField(max_length=30)),
                ('open_time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Product_Server',
            },
        ),
    ]
