# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-04 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('AccountID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=11, unique=True)),
                ('username', models.CharField(max_length=10, null=True)),
                ('channel', models.IntegerField(null=True)),
                ('from_id', models.CharField(max_length=11, null=True)),
                ('token', models.CharField(max_length=20, null=True)),
                ('time', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('access_token', models.CharField(blank=True, max_length=100)),
                ('refresh_token', models.CharField(blank=True, max_length=100)),
                ('expires_in', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ('AccountID',),
            },
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileImgURL', models.URLField()),
                ('NickName', models.CharField(max_length=5)),
                ('PhoneNumber', models.IntegerField()),
                ('CarrierCode', models.IntegerField(default=0)),
                ('InviterID', models.IntegerField()),
                ('Address', models.CharField(max_length=30)),
                ('Mail', models.EmailField(max_length=254)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AccountInfo',
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountName', models.CharField(max_length=10)),
                ('AccountLevelCode', models.IntegerField(default=0)),
                ('UserID', models.IntegerField()),
                ('UserName', models.CharField(max_length=10)),
                ('GenderCode', models.IntegerField(default=0)),
                ('UserImgURL', models.URLField()),
                ('RegisterDate', models.DateTimeField()),
                ('JoinIP', models.CharField(max_length=39)),
                ('ChannelCode', models.IntegerField()),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountStatus', models.IntegerField(default=0)),
                ('NameAuthStatus', models.IntegerField(default=0)),
                ('ContactStatus', models.IntegerField(default=0)),
                ('CarrierAuthStatus', models.IntegerField(default=0)),
                ('DeviceAuthStatus', models.IntegerField(default=0)),
                ('BankCardAuthStatus', models.IntegerField(default=0)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountStatus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AccountStatus',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('udid', models.IntegerField()),
                ('device_name', models.CharField(max_length=30)),
                ('device_mode', models.CharField(max_length=30)),
                ('system_version', models.CharField(max_length=10)),
                ('app_version', models.CharField(max_length=10)),
                ('jail_broken', models.IntegerField(default=0)),
                ('access_gps', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('time', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Devices',
            },
        ),
    ]
