# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-21 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Agent',
            fields=[
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=16, null=True)),
                ('hid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('agentname', models.CharField(max_length=16, null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Product_Agent',
            },
        ),
    ]
