# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0003_auto_20171221_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_agent',
            name='agentname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
